// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PGConnecter is an autogenerated mock type for the PGConnecter type
type PGConnecter struct {
	mock.Mock
}

// Exec provides a mock function with given fields: query
func (_m *PGConnecter) Exec(query string) error {
	ret := _m.Called(query)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(query)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
