version: '2'

services:
  web:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - "80:80"
    env_file: .env
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - php
    volumes_from:
      - app-data

  php:
    build: ./php/
    container_name: "php7-fpm"
    env_file: .env
    expose:
      - 9000
    links:
      - mariadb
    volumes_from:
      - app-data

  mariadb:
    image: mariadb:latest
    volumes:
      - ${PERSISTENT_DB_MARIADB}:/var/lib/mariadb
      - ${PERSISTENT_DB_MYSQL}:/var/lib/mysql
      - ${DB_CONFIG}:/etc/mysql/my.cnf
    container_name: "mariadb"
    env_file: .env

  app-data:
    image: php:7.0-fpm
    container_name: "app-data"
    volumes:
      - ${PERSISTENT_APP}:/var/www/html
    command: "true"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin"
    ports:
      - 8080:80
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
